<a href="https://colab.research.google.com/github/saimeonver/PythonExercise/blob/main/PandasExercises2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#görev 14: age değişkenindeki boş değerleri age değişkeninin
#medyanı ile doldurun

import seaborn as sns
import pandas as pd
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
age_medyan = df["age"].median()
df["age"] = df["age"].fillna(age_medyan)

In [ ]:
df[df["age"].isnull()]

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone]
Index: []

In [ ]:
#görev 15: survived deişkneinin pclass ve cinsiyet değişkenleri kırılımnda
#sum, count, mean değerlerini bulun
df.pivot_table("survived", ["pclass", "sex"], aggfunc=["sum","count","mean"])

                   sum    count      mean
              survived survived  survived
pclass sex
1      female       91       94  0.968085
       male         45      122  0.368852
2      female       70       76  0.921053
       male         17      108  0.157407
3      female       72      144  0.500000
       male         47      347  0.135447

In [3]:
#görev 16: 30 yaş aştında olanlar 1, 30 a eşit olanlar 0 verecek fonks yaz
#yazdığnda fonsiyonda titanic veri setinde age_flag adndan bir değişken
#oluştur(apply ve lambda kullan)

def age_flag_func(x):
    if x < 30:
        return 1
    else:
        return 0



df["age_flag"] = df["age"].apply(lambda x: age_flag_func(x) )

In [4]:
#diğer yol
df["age_flag"] = df["age"].apply(lambda x:1 if x<30 else 0 )

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_flag
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0

In [5]:
#görev 17: seaborn kütüphanesinden tips veerisini tanımlayın
import seaborn as sns
import pandas as pd

df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [6]:
df.shape

(244, 7)

In [ ]:
#görev 18: time değişkenini kategorilerine (dinner ,lunch) a göre total_bill
#değerlerinin toplamoıını, min,max,ortalamasını bulunuz

df.groupby("time").agg({"total_bill":["sum","min","max","mean"]})

/tmp/ipython-input-3910555237.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("time").agg({"total_bill":["sum","min","max","mean"]})

       total_bill
              sum   min    max       mean
time
Lunch     1167.47  7.51  43.11  17.168676
Dinner    3660.30  3.07  50.81  20.797159

In [ ]:
#görev 19: günlere ve time a göre total_bill değerinin toplamını
#min, max ve ortalmasını bulun

df.groupby(["day","time"]).agg({"total_bill": ["sum","min","max","mean"]})

/tmp/ipython-input-1654652465.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["day","time"]).agg({"total_bill": ["sum","min","max","mean"]})

            total_bill
                   sum    min    max       mean
day  time
Thur Lunch     1077.55   7.51  43.11  17.664754
     Dinner      18.78  18.78  18.78  18.780000
Fri  Lunch       89.92   8.58  16.27  12.845714
     Dinner     235.96   5.75  40.17  19.663333
Sat  Lunch        0.00    NaN    NaN        NaN
     Dinner    1778.40   3.07  50.81  20.441379
Sun  Lunch        0.00    NaN    NaN        NaN
     Dinner    1627.16   7.25  48.17  21.410000

In [ ]:
#görev 20: Lunch zamanına göre ve kadın müşterilere ait total_bill ve tip değer
#lerinin day 2 e göre toplamnın min, max ve ortalamsını bulunuz

df_new = df.loc[(df["sex"]=="Female")&(df["time"]=="Lunch")]

In [ ]:
df_new.groupby("day").agg({"total_bill": ["sum","min","max","mean"],
                           "tip": ["sum","min","max","mean"]})

/tmp/ipython-input-41863708.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_new.groupby("day").agg({"total_bill": ["sum","min","max","mean"],

     total_bill                            tip
            sum    min    max      mean    sum   min   max      mean
day
Thur     516.11   8.35  43.11  16.64871  79.42  1.25  5.17  2.561935
Fri       55.76  10.09  16.27  13.94000  10.98  2.00  3.48  2.745000
Sat        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN
Sun        0.00    NaN    NaN       NaN   0.00   NaN   NaN       NaN

In [ ]:
#görev21: sizei 3 ten küçük total_bill 10'dan büyük olan sipraişlerin
#ortalaması nedir(loc kullan)

df.loc[(df["size"]<3) & (df["total_bill"]>10), "total_bill"].mean()

np.float64(17.184965034965035)

In [ ]:
#görev22  :total_bill_tip_sum adından yeni bir dğeişken oluştur. her bir
#müşterinin ödediği totalbill ve tp in toplamını ver

df["total_bill_tip_sum"] = df["total_bill"] + df["tip"]
df.head()

   total_bill   tip     sex smoker  day    time  size  total_bill_tip_sum
0       16.99  1.01  Female     No  Sun  Dinner     2               18.00
1       10.34  1.66    Male     No  Sun  Dinner     3               12.00
2       21.01  3.50    Male     No  Sun  Dinner     3               24.51
3       23.68  3.31    Male     No  Sun  Dinner     2               26.99
4       24.59  3.61  Female     No  Sun  Dinner     4               28.20

In [ ]:
#görev23 : total_bill_tip_sum değişkeine göre büyükten küçüğe sırala
#ilk 30 kişiyi yen df e ata

df_new_30 = df["total_bill_tip_sum"].sort_values(ascending=False).head(30)

In [ ]:
df_new_30

170    60.81
212    57.33
59     55.00
156    53.17
182    48.85
197    48.11
23     47.00
102    46.80
142    46.19
95     44.90
184    43.55
112    42.07
207    41.73
56     41.01
141    41.00
238    40.50
11     40.26
52     40.01
85     40.00
47     38.40
180    38.33
179    38.18
83     37.68
39     36.27
167    36.21
175    36.01
44     36.00
173    35.03
116    35.00
155    34.99
Name: total_bill_tip_sum, dtype: float64